Leewonno/project2

static/css/login.css, views/login.ejs
=> [Design login]

static/css/index.css, static/css/login.css, static/css/signup.css, views/login.ejs, views/signup.ejs
login page design 수정 및 sigup page 완료
=> UPDATE design login, signup

package-lock.json, package.json
=> [Chore] mysql 모듈 mysql2 모듈로 변경

database/db.js, database/model/chat.js, database/model/chatroom.js, database/model/comment.js, database/model/p_like.js, database/model/playlist.js, database/model/s_like.js
=> [Add] DB 모델링 관계 설정 추가

index.js, static/css/footer.css, static/css/header.css, static/css/playbar.css, static/css/playlist.css, static/css/sort.css, views/mypage.ejs
=> [Design] 수정

controller/song.controller.js, index.js, package-lock.json, package.json, router/song.router.js, utils/upload.js, views/song_upload.ejs
- 관리자 곡 업로드
- 곡 상세보기 
- merge conflict 해결
=> [Feat] 관리자 곡 업로드, 곡 상세보기 기능 구현 - 1차

utils/upload.js
=> [Fix] s3 이미지 저장 파일명 수정

controller/song.controller.js, database/model/song.js
- 곡 테이블 좋아요 컬럼 추가
- 곡 업로드 시 좋아요 수 추가
=> [Add] 곡 테이블 좋아요 컬럼 추가 및 곡 업로드 시 좋아요 수 추가

controller/song.controller.js, router/song.router.js, utils/upload.js
-  메인 페이지 최신 발매일 순 곡 정렬
- 파일 크기 제한 변경
=> [Feat] 메인 페이지 최신 발매일 곡 정렬 및 파일 제한 수정

controller/song.controller.js
=> [Fix] 메인 페이지 최신 발매일순 정렬 코드 수정

controller/song.controller.js, router/song.router.js, static/css/song.css, views/song.ejs
- 곡 상세 페이지 데이터 조회
- 곡 상세 페이지 CSS 디자인 임시 수정
- 곡 상세 페이지 내에서 좋아요 토글 기능 추가
=> [Feat] 곡 상세 페이지 조회 및 좋아요 기능 추가

controller/main.controller.js, router/app.router.js, static/css/index.css, views/index.ejs
=> [Feat] 메인 페이지 정렬 기능 수정 추가

controller/song.controller.js, controller/user.controller.js, index.js, middleware/auth.middleware.js, router/app.router.js, router/song.router.js, router/user.router.js, static/js/logout.js, utils/jwt.js, views/index.ejs, views/profile.ejs, views/signin.ejs, views/song.ejs
- jwt token 생성, 검증 미들웨어 생성
- 로그인 시 token 쿠키 저장 구현
- 로그아웃 쿠키 삭제로 변경
- 회원 정보 수정 등 프로필 페이지 관련 jwt token 임시 적용 (수정 필요)
- 곡 상세 페이지, 좋아요 jwt token 적용
=> [Add] JWT token 적용 및 기타 수정

config/config.js, controller/song.controller.js, database/db.js, database/model/comment.js, router/song.router.js, static/css/song.css, utils/formatToKST.js, views/song.ejs
- 기타 설정 추가
- 곡 상세페이지 댓글 목록 구현
- 댓글 작성 ejs까지 구현 완료
- 댓글 수정, 삭제 Back-End 작업까지 구현
=> [Feat] 기타 설정 추가 및 곡 상세 페이지 댓글 목록, 생성 추가

utils/formatToKST.js
=> [Docs] 주석 삭제

database/db.js, database/model/chat_member.js
=> [Feat] 채팅 멤버 테이블 모델링 작업

controller/song.controller.js, controller/user.controller.js, router/song.router.js, router/user.router.js, static/css/sort.css, views/sort.ejs
- 곡 정렬 페이지 최신순 정렬
- 곡 정렬 페이지 좋아요순 정렬
- 장르별 카테고리 선택 시 토글 기능 추가
- 장르별 정렬 기능 구현
=> [Feat] 곡 정렬 페이지 최신순, 좋아요순, 장르별 정렬 기능 구현

static/css/sort.css, views/layouts/layout.ejs, views/sort.ejs
- 정렬 페이지 CSS 수정
- 헤더 메뉴 선택 시 정렬 페이지 이동 수정
=> [Fix] 정렬페이지 헤더이동 수정

views/song.ejs
- 곡 상세 댓글 작성 시 리스트의 첫번 째 요소로 추가될 수 있게 순서 수정
=> [Fix] 곡 상세 댓글 작성 시 리스트 요소 추가 순서 수정

controller/main.controller.js, static/css/search.css, static/js/pageload.js, views/search.ejs
=> [Feat] 검색 기능 구현

controller/song.controller.js, router/song.router.js
=> [Feat] 정렬 페이지, 댓글 페이징 처리 로직  추가

database/model/playlist.js
=> [Add] Playlist model DB 컬럼 수정 반영

controller/user.controller.js
=> [Add] 회원가입 유저 아이디 중복확인 Back 코드 추가

controller/user.controller.js, router/user.router.js
=> [Fix] 회원가입 중복체크 로직 분리

controller/main.controller.js, controller/song.controller.js, static/css/index.css, views/index.ejs
- 메인페이지 데이터 수정 추가 및 정렬페이지 비회원 접근 수정
=> [Add] 메인페이지 데이터 수정 추가 및 정렬페이지 비회원 접근 수정

controller/main.controller.js, router/app.router.js, static/css/header.css, static/css/index.css, views/index.ejs
=> [Design] 메인페이지 디자인 수정

static/css/index.css, views/index.ejs
=> [Design] 메인 페이지 디자인 작업

controller/main.controller.js, controller/song.controller.js, router/app.router.js, views/index.ejs
=> [Feat] 메인페이지 정렬 기능 추가

controller/main.controller.js, static/css/index.css, views/index.ejs
=> [Design] 메인페이지 버튼 등 배치, 디자인 수정

controller/main.controller.js, router/app.router.js, static/css/search.css, views/search.ejs
- 검색 페이지 플레이리스트 좋아요 기능 추가
- 검색 페이지 전체 디자인 1차 수정
=> [Feat] 검색 페이지 플레이리스트 좋아요 기능 추가 및 전체 디자인 수정

static/css/index.css, static/css/search.css
=> [Design] 검색 페이지 디자인 수정

views/index.ejs, views/search.ejs
=> [Add] 메인페이지, 검색페이지 플레이리스트 함수 수정
